// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP-8l26LAYOvLP7k4gkzggfbBMaQouH44',
    appId: '1:52747009939:web:c5b35685c525619f4ab266',
    messagingSenderId: '52747009939',
    projectId: 'fir-userauth-5de5b',
    authDomain: 'fir-userauth-5de5b.firebaseapp.com',
    storageBucket: 'fir-userauth-5de5b.appspot.com',
    measurementId: 'G-K6D2BC05QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uZXDJ-VAieFTfCMAVvHnFVWGufBJy68',
    appId: '1:52747009939:android:28ccb2b9d0bcbb5d4ab266',
    messagingSenderId: '52747009939',
    projectId: 'fir-userauth-5de5b',
    storageBucket: 'fir-userauth-5de5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuDdPgEYVvnJLDuCpWzSQdB78YeWpDOE',
    appId: '1:52747009939:ios:44b1fdbd99934c304ab266',
    messagingSenderId: '52747009939',
    projectId: 'fir-userauth-5de5b',
    storageBucket: 'fir-userauth-5de5b.appspot.com',
    iosClientId: '52747009939-3pui8pruil6seersaqu0qme718tijsfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUserauthfull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuDdPgEYVvnJLDuCpWzSQdB78YeWpDOE',
    appId: '1:52747009939:ios:44b1fdbd99934c304ab266',
    messagingSenderId: '52747009939',
    projectId: 'fir-userauth-5de5b',
    storageBucket: 'fir-userauth-5de5b.appspot.com',
    iosClientId: '52747009939-3pui8pruil6seersaqu0qme718tijsfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUserauthfull',
  );
}
